Configurations:
  - WebApplications

WebApplications:
  Items:
    - Name: TestApp3
      PhysicalPath: C:\InetPub\WebApplications3
      SslFlags: Ssl
      Website: TestSite3
      EnabledProtocols:
        - http
        - https
      WebAppPool: AISAppPool
      AuthenticationInfo:
        Anonymous: false
        Basic: false
        Digest: false
        Windows: true

DscTagging:
  Layers:
    - '[x={ Get-DatumSourceFile -Path $File } =]'
